/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'lab3' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f3xx.h"

/* ARM::CMSIS-Compiler:STDOUT:ITM@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_ITM            /* CMSIS-Compiler STDOUT: ITM */
/* Keil::Device&Standalone:Startup@1.11.3 */
#define RTE_DEVICE_STARTUP_STM32F3XX    /* Device Startup for STM32F3 */


#endif /* RTE_COMPONENTS_H */
